version: '3'
services:
  app:
    build:
      context: app
    ports:
      - "5000"

  nginx:
    image : nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"


# enter a virtual env first 
# python3 -m venv venv


# "5000:5000" means mapping port from container to port in system
# https://www.youtube.com/watch?v=42Q65H8ch7U
# run the container, check server in devtools
# then scale
# docker-compose up -d --build --scale app=3
# flag d means application isnt attached to container during runtime

# when you run the scale command it may bring error because port is already in use

# check your containers are running 
# docker ps

# multiple servers running, user has to enter port numbers manually 

# run command for scaling after you've set up everything
